version: "3.3"
services:
  postgres:
    container_name: bot_postgres_db
    image: postgres:15.1
    environment:
      POSTGRES_DB: "quiz-travel"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user1234"
    ports:
      - "6000:5432"
