"""initial

Revision ID: 467786411eb1
Revises: 
Create Date: 2023-09-09 16:30:45.270684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467786411eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('team', sa.Enum('marik', 'marea', name='team'), nullable=True),
    sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__user')),
    sa.UniqueConstraint('chat_id', name=op.f('uq__user__chat_id')),
    sa.UniqueConstraint('username', name=op.f('uq__user__username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
